/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "alarm_notification-group": () => import("@/views/alarm/notification-group/index.vue"),
  "alarm_notification-record": () => import("@/views/alarm/notification-record/index.vue"),
  "alarm_warning-message": () => import("@/views/alarm/warning-message/index.vue"),
  apply_plugin: () => import("@/views/apply/plugin/index.vue"),
  apply_service: () => import("@/views/apply/service/index.vue"),
  "automation_linkage-edit": () => import("@/views/automation/linkage-edit/index.vue"),
  "automation_scene-edit": () => import("@/views/automation/scene-edit/index.vue"),
  "automation_scene-linkage": () => import("@/views/automation/scene-linkage/index.vue"),
  "automation_scene-manage": () => import("@/views/automation/scene-manage/index.vue"),
  dashboard_analysis: () => import("@/views/dashboard/analysis/index.vue"),
  "dashboard_mobile-panel": () => import("@/views/dashboard/mobile-panel/index.vue"),
  dashboard_panel: () => import("@/views/dashboard/panel/index.vue"),
  dashboard_workbench: () => import("@/views/dashboard/workbench/index.vue"),
  "data-service_rule-engine": () => import("@/views/data-service/rule-engine/index.vue"),
  "device-details-app": () => import("@/views/device-details-app/index.vue"),
  "device_config-detail": () => import("@/views/device/config-detail/index.vue"),
  "device_config-edit": () => import("@/views/device/config-edit/index.vue"),
  device_config: () => import("@/views/device/config/index.vue"),
  "device_details-child": () => import("@/views/device/details-child/index.vue"),
  device_details: () => import("@/views/device/details/index.vue"),
  "device_grouping-details": () => import("@/views/device/grouping-details/index.vue"),
  device_grouping: () => import("@/views/device/grouping/index.vue"),
  device_manage: () => import("@/views/device/manage/index.vue"),
  "device_service-access": () => import("@/views/device/service-access/index.vue"),
  "device_service-details": () => import("@/views/device/service-details/index.vue"),
  device_template: () => import("@/views/device/template/index.vue"),
  home: () => import("@/views/home/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  manage_role: () => import("@/views/manage/role/index.vue"),
  "manage_user-detail": () => import("@/views/manage/user-detail/[id].vue"),
  manage_user: () => import("@/views/manage/user/index.vue"),
  management_api: () => import("@/views/management/api/index.vue"),
  management_auth: () => import("@/views/management/auth/index.vue"),
  management_notification: () => import("@/views/management/notification/index.vue"),
  management_role: () => import("@/views/management/role/index.vue"),
  management_route: () => import("@/views/management/route/index.vue"),
  management_setting: () => import("@/views/management/setting/index.vue"),
  management_user: () => import("@/views/management/user/index.vue"),
  "personal-center": () => import("@/views/personal-center/index.vue"),
  "rule-engine": () => import("@/views/rule-engine/index.vue"),
  "system-management-user_system-log": () => import("@/views/system-management-user/system-log/index.vue"),
  "user-center": () => import("@/views/user-center/index.vue"),
  "visualization_thingsvis-dashboards": () => import("@/views/visualization/thingsvis-dashboards/index.vue"),
  "visualization_thingsvis-editor": () => import("@/views/visualization/thingsvis-editor/index.vue"),
  "visualization_thingsvis-menu-dashboard": () => import("@/views/visualization/thingsvis-menu-dashboard/index.vue"),
  "visualization_thingsvis-preview": () => import("@/views/visualization/thingsvis-preview/index.vue"),
  visualization_thingsvis: () => import("@/views/visualization/thingsvis/index.vue"),
};
